# Generated by Django 5.1.3 on 2024-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_cookie_packetinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetinfo',
            name='dst_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packetinfo',
            name='packet_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packetinfo',
            name='protocol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packetinfo',
            name='src_ip',
            field=models.CharField(max_length=100),
        ),
    ]
